#ifndef XIAOZHI_DEFAULTS_H
#define XIAOZHI_DEFAULTS_H

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_OTA_URL
#  define XIAOZHI_DEFAULT_OTA_URL \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_OTA_URL
#else
#  define XIAOZHI_DEFAULT_OTA_URL \
     "https://api.tenclass.net/xiaozhi/ota/"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_LANGUAGE
#  define XIAOZHI_DEFAULT_LANGUAGE \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_LANGUAGE
#else
#  define XIAOZHI_DEFAULT_LANGUAGE "zh-CN"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_WIFI_IFNAME
#  define XIAOZHI_DEFAULT_WIFI_IFNAME \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_WIFI_IFNAME
#else
#  define XIAOZHI_DEFAULT_WIFI_IFNAME "wlan0"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_IDENTITY_PATH
#  define XIAOZHI_DEFAULT_IDENTITY_PATH \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_IDENTITY_PATH
#else
#  define XIAOZHI_DEFAULT_IDENTITY_PATH "/data/gemini-s1/xz_client_id"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CREDENTIALS_PATH
#  define XIAOZHI_DEFAULT_CREDENTIALS_PATH \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CREDENTIALS_PATH
#else
#  define XIAOZHI_DEFAULT_CREDENTIALS_PATH "/data/gemini-s1/xz_cloud.json"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CA_FILE
#  define XIAOZHI_DEFAULT_CA_FILE \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CA_FILE
#else
#  define XIAOZHI_DEFAULT_CA_FILE ""
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_BOARD_NAME
#  define XIAOZHI_DEFAULT_BOARD_NAME \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_BOARD_NAME
#else
#  define XIAOZHI_DEFAULT_BOARD_NAME "gemini-s1"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CHIP_MODEL
#  define XIAOZHI_DEFAULT_CHIP_MODEL \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_CHIP_MODEL
#else
#  define XIAOZHI_DEFAULT_CHIP_MODEL "r528"
#endif

#ifdef CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_FIRMWARE_VERSION
#  define XIAOZHI_DEFAULT_FIRMWARE_VERSION \
     CONFIG_LVX_USE_DEMO_CONTEST2026_208_XIAOZHI_FIRMWARE_VERSION
#else
#  define XIAOZHI_DEFAULT_FIRMWARE_VERSION "0.1.0"
#endif

#define XIAOZHI_DEFAULT_APPLICATION_NAME "moxinzhi-openvela"
#define XIAOZHI_DEFAULT_USER_AGENT \
  "moxinzhi-openvela/" XIAOZHI_DEFAULT_FIRMWARE_VERSION

#endif /* XIAOZHI_DEFAULTS_H */
