/****************************************************************************
 * Contest 2026 team 208 - platform configuration fallbacks
 ****************************************************************************/

#ifndef __GS1_CONFIG_H
#define __GS1_CONFIG_H

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_ROOT
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_ROOT "/data/gemini-s1"
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_WIFI_IFNAME
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_WIFI_IFNAME "wlan0"
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_WORKER_STACKSIZE
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_WORKER_STACKSIZE 32768
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_RECORD_MAX_FILES
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_RECORD_MAX_FILES 20
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_RECORD_MAX_BYTES
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_RECORD_MAX_BYTES \
     67108864
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_SAMPLE_RATE
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_SAMPLE_RATE 16000
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CHANNELS
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CHANNELS 1
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_BITS
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_BITS 16
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CHANNEL_MAP
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CHANNEL_MAP 0
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_STREAM_BUFFER_BYTES
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_STREAM_BUFFER_BYTES \
     32768
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CAPTURE_DEVICE
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_CAPTURE_DEVICE \
     "/dev/audio/pcm0c"
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_PLAYBACK_DEVICE
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_AUDIO_PLAYBACK_DEVICE \
     "/dev/audio/pcm0p"
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_NTP_RESTART_SECONDS
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_NTP_RESTART_SECONDS 12
#endif

#ifndef CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_NTP_MAX_RESTARTS
#  define CONFIG_LVX_USE_DEMO_CONTEST2026_208_PLATFORM_NTP_MAX_RESTARTS 2
#endif

#endif /* __GS1_CONFIG_H */
