############################################################################
# Contest 2026 team 208 MoXin Smart Learning - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = lvgl_screen_test
PRIORITY  = $(CONFIG_LVX_USE_DEMO_CONTEST2026_208_LVGL_SCREEN_TEST_PRIORITY)
STACKSIZE = $(CONFIG_LVX_USE_DEMO_CONTEST2026_208_LVGL_SCREEN_TEST_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_208_LVGL_SCREEN_TEST)

MAINSRC = hello_app_main.c
CSRCS   = moxinzhi_ai_service.c moxinzhi_diag.c moxinzhi_model.c \
          moxinzhi_storage.c moxinzhi_ui.c

include $(APPDIR)/Application.mk
